---
- name: Stop and Uninstall Nginx
  hosts: all
  become: true

  tasks:
    - name: Stop Nginx
      service: 
        name: nginx
        state: stopped

    - name: Remove Nginx
      apt:
        name: nginx
        state: absent



